spring:
  jpa:
    properties:
      hibernate:
        default_schema: public
        jdbc:
          time_zone: UTC

    database: POSTGRESQL
    show-sql: true
    generate-ddl: true


    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop


  datasource:
    url: jdbc:postgresql://localhost:5432/prod
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver

